---
- name: Install Mongo
  hosts: all
  become: true
  tasks:
  - name: Apt key
    apt_key:
      id: E52529D4
      keyserver: keyserver.ubuntu.com
      state: present

  - name: Add apt repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
      state: present

  - name: Update and install mongo
    apt:
      force_apt_get: yes
      state: present
      update_cache: yes
      name: mongodb-org

  - name: Enable Mongo
    systemd:
      name: mongod
      enabled: yes
...
