---

## DB Section

 - name: Configure MongoDB
   hosts: db
   tags: db-tag
   become: true
   vars:
    mongo_bind_ip: 0.0.0.0

# DB TASKS

   tasks:
   - name: Change mongo config file
     template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
     notify: restart mongod

# DB HANDLERS

   handlers:
   - name: restart mongod
     service: name=mongod state=restarted

## APP Section

 - name: Configure hosts & deploy application
   hosts: app
   tags: app-tag
   become: true
   vars:
    db_host: 10.132.15.197

# APP TASKS

   tasks:
   - name: Add unit file for Puma
     copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
     notify: reload puma

   - name: Add config for DB connection
     template:
      src: templates/db_config.j2
      dest: /home/ak/db_config

   - name: enable puma
     systemd: name=puma enabled=yes

# APP HANDLERS

   handlers:
   - name: reload puma
     systemd: name=puma state=restarted

## DEPLOY Section

 - name: Deploy application
   hosts: app
   tags: deploy-tag
   become: true

# DEPLOY TASKS

   tasks:
   - name: Fetch the latest version of application code
     git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ak/reddit
      version: monolith
     tags: deploy-tag
     notify: restart puma

   - name: Bundle install
     bundler:
      state: present
      chdir: /home/ak/reddit
     tags: deploy-tag

# DEPLOY HANDLERS

   handlers:
   - name: restart puma
     systemd: name=puma state=restarted

...
