$git_install = <<-SCRIPT
sudo apt install git
sudo apt install mc -y
mkdir ansible && cd ansible
git clone -b ansible-4 https://github.com/Otus-DevOps-2019-11/alex-k812_infra.git
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.boot_timeout = 30
  #config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=755", "fmode=664"]
  config.ssh.insert_key = false
#  config.ssh.username = "ak"
#  config.ssh.private_key_path = ['C:\Users\AK\Documents\alex-k812_infra-ansible-4\ansible\ssh\ak', '~/.ssh/id_rsa']
#  config.vm.provision "file", source: "C:/Users/AK/Documents/alex-k812_infra-ansible-4/ansible/ssh/ak.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell",
    inline: "sudo apt-get update"
  config.vm.provider :virtualbox do |v|
#    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/ansible", "1"]
    v.memory = 512
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "192.168.10.3"
#    db.vm.provision "shell", inline: "cat /vagrant/ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.define "app" do |app|
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "192.168.10.2"
#    app.vm.provision "shell", inline: "cat /vagrant/ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.define "controller" do |controller|
    controller.vm.network :private_network, ip: "192.168.10.254"
    controller.vm.hostname = "controller"
    controller.vm.provision "shell", inline: $git_install
#    controller.vm.provision "file", source: "ssh/id_rsa", destination: "~/.ssh/id_rsa"
#    controller.vm.provision "shell", inline: "chmod 400 ~/.ssh/id_rsa"
    controller.vm.provision :ansible_local do |ansible|
      ansible.playbook = "/vagrant/playbooks/site.yml"
      ansible.verbose = true
      ansible.install = true
      ansible.limit = "all"
      ansible.groups = {
        "db" => ["dbserver"],
        "db:vars" => {"mongo_bind_ip" => "0.0.0.0"},
        "app" => ["appserver"],
        "app:vars" => { "db_host" => "192.168.10.3"}
      }
      ansible.extra_vars = {
        "deploy_user" => "ubuntu"
      }
      ansible.inventory_path = "inventory"
    end
  end
end
